version: '3'
services:
  signaling:
    container_name: "signaling"
    # network_mode: "host"
    image: "sigbase:0.1"
    restart: "always"
    tty: true
    cap_add:
    - NET_ADMIN
    ports:
      - "443:443" 
    devices:
      - "/dev/net/tun:/dev/net/tun"


    # volumes:
    #   - "./:/usr/src"
    
    # command: ifconfig
